apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runtime
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  runtime.toml: |
    {{- include "worker.runtime" . | nindent 4 }}
