# chapter: ml/08-tinyllm/p12-post-training/01-supervised-fine-tuning.md
from __future__ import annotations
from typing import Sequence
import numpy as np

def render_chat(messages: Sequence[dict[str, str]], tokenizer: object) -> list[int]: ...
def assistant_loss_mask(messages: Sequence[dict[str, str]], tokenizer: object) -> tuple[list[int], list[bool]]: ...
def pack(examples: Sequence[tuple[Sequence[int], Sequence[bool]]], seq_len: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
