//! kvpush: a client of tl.kv.v1.KvTransferService over the vendored stubs
//! (contracts/rust/tl-proto, generated by prost and tonic).
//!
//! `push` is the prefill side of a KV hand-off in miniature (L10.6 does it
//! for real): ask which blocks the other side already holds (HasBlocks, a
//! unary call), then send every block in order on one client stream
//! (PushKv), with an empty payload for the blocks already there, and read
//! the single acknowledgement at the end.

use tl_proto::tl::kv::v1::kv_transfer_service_client::KvTransferServiceClient;
use tl_proto::tl::kv::v1::{HasBlocksRequest, KvChunk, ReleaseRequest};

/// CRC-32C (Castagnoli, reflected polynomial 0x82F63B78), bit by bit:
/// `crc32c(b"123456789") == 0xE3069283`.
pub fn crc32c(data: &[u8]) -> u32 {
    // SOLUTION-BEGIN lang.10
    let mut crc = !0u32;
    for &b in data {
        crc ^= b as u32;
        for _ in 0..8 {
            crc = if crc & 1 == 1 { (crc >> 1) ^ 0x82F6_3B78 } else { crc >> 1 };
        }
    }
    !crc
    // SOLUTION-END
}

/// The toy block hash: FNV-1a 64 of the payload, never 0 (0 marks a tail).
pub fn block_hash(data: &[u8]) -> u64 {
    // SOLUTION-BEGIN lang.10
    let mut h = 0xCBF2_9CE4_8422_2325u64;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01B3);
    }
    if h == 0 {
        1
    } else {
        h
    }
    // SOLUTION-END
}

/// `len` deterministic bytes for block `index` of `seed`.
pub fn payload(seed: u64, index: u32, len: usize) -> Vec<u8> {
    // SOLUTION-BEGIN lang.10
    let mut x = seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ (index as u64 + 1);
    (0..len)
        .map(|_| {
            x = x.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            (x >> 56) as u8
        })
        .collect()
    // SOLUTION-END
}

/// What a push did.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PushReport {
    pub present: Vec<bool>,
    pub received: u32,
    pub deduped: u32,
}

/// The canonical name of a gRPC status code (`DATA_LOSS`, ...).
pub fn code_name(c: tonic::Code) -> &'static str {
    // SOLUTION-BEGIN lang.10
    use tonic::Code::*;
    match c {
        Ok => "OK",
        Cancelled => "CANCELLED",
        Unknown => "UNKNOWN",
        InvalidArgument => "INVALID_ARGUMENT",
        DeadlineExceeded => "DEADLINE_EXCEEDED",
        NotFound => "NOT_FOUND",
        AlreadyExists => "ALREADY_EXISTS",
        PermissionDenied => "PERMISSION_DENIED",
        ResourceExhausted => "RESOURCE_EXHAUSTED",
        FailedPrecondition => "FAILED_PRECONDITION",
        Aborted => "ABORTED",
        OutOfRange => "OUT_OF_RANGE",
        Unimplemented => "UNIMPLEMENTED",
        Internal => "INTERNAL",
        Unavailable => "UNAVAILABLE",
        DataLoss => "DATA_LOSS",
        Unauthenticated => "UNAUTHENTICATED",
    }
    // SOLUTION-END
}

/// Connects to `addr` (`http://127.0.0.1:<port>`).
async fn client(addr: &str) -> Result<KvTransferServiceClient<tonic::transport::Channel>, tonic::Status> {
    // SOLUTION-BEGIN lang.10
    KvTransferServiceClient::connect(addr.to_string()).await.map_err(|e| tonic::Status::unavailable(e.to_string()))
    // SOLUTION-END
}

/// HasBlocks, then PushKv of every block of `handle`: the payload for a
/// block the server lacks, an empty payload for one it holds. `corrupt`
/// flips one bit of the first payload after its CRC was computed.
pub async fn push(addr: &str, handle: &str, payloads: &[Vec<u8>], kv_format: u32, corrupt: bool) -> Result<PushReport, tonic::Status> {
    // SOLUTION-BEGIN lang.10
    let mut c = client(addr).await?;
    let hashes: Vec<u64> = payloads.iter().map(|p| block_hash(p)).collect();
    let present = c.has_blocks(HasBlocksRequest { block_hashes: hashes.clone(), kv_format }).await?.into_inner().present;
    if present.len() != hashes.len() {
        return Err(tonic::Status::internal("HasBlocks answered for a different number of blocks"));
    }
    let total = payloads.len() as u32;
    let chunks: Vec<KvChunk> = payloads
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let (mut body, crc) = if present[i] { (Vec::new(), 0) } else { (p.clone(), crc32c(p)) };
            if corrupt && i == 0 && !body.is_empty() {
                body[0] ^= 1;
            }
            KvChunk { handle_id: handle.to_string(), block_hash: hashes[i], block_index: i as u32, n_blocks_total: total, kv_format, payload: body, crc32c: crc }
        })
        .collect();
    let ack = c.push_kv(tokio_stream::iter(chunks)).await?.into_inner();
    Ok(PushReport { present, received: ack.blocks_received, deduped: ack.blocks_deduped })
    // SOLUTION-END
}

/// Release(handle).
pub async fn release(addr: &str, handle: &str) -> Result<(), tonic::Status> {
    // SOLUTION-BEGIN lang.10
    client(addr).await?.release(ReleaseRequest { handle_id: handle.to_string() }).await?;
    Ok(())
    // SOLUTION-END
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crc32c_check_value() {
        assert_eq!(crc32c(b"123456789"), 0xE306_9283);
    }

    #[test]
    fn payloads_are_deterministic_and_distinct() {
        assert_eq!(payload(1, 0, 16), payload(1, 0, 16));
        assert_ne!(payload(1, 0, 16), payload(1, 1, 16));
        assert_ne!(block_hash(&payload(1, 0, 16)), 0);
    }
}
