{{- if .Values.runtime }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runtime
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  runtime.toml: |
    {{- toToml .Values.runtime | nindent 4 }}
{{- end }}
