"""Mutant specs for the tokenizer modules: one dict per mutant (see mutants.py).

Semantic mutants (tier `semantic`, required) plant a chapter pitfall; auto
mutants (tier `auto`) are the operators of DESIGN 5.6 applied by hand to the
lines the tests should guard.
"""

B = "python/tinyllm/tok/base.py"
C = "python/tinyllm/tok/char.py"


def sem(mid, unit, op, private, *edits):
    return {"mid": mid, "unit": unit, "tier": "semantic", "operator": op,
            "public": "", "private": private, "edits": list(edits)}


def auto(mid, unit, op, public, private, *edits):
    return {"mid": mid, "unit": unit, "tier": "auto", "operator": op,
            "public": public, "private": private, "edits": list(edits)}


L1_1 = [
    sem("s01", C, "pitfall-2", "vocab in first-appearance order, not code point order",
        ("        seen: set[str] = set()\n        for t in texts:\n            seen.update(t)\n        vocab += sorted(seen, key=ord)\n",
         "        seen: dict[str, None] = {}\n        for t in texts:\n            seen.update(dict.fromkeys(t))\n        vocab += list(seen)\n")),
    sem("s02", C, "unk-first", "<unk> after the other specials",
        ('        vocab = ["<unk>"]\n        roles = {"unk": 0}\n',
         '        vocab = []\n        roles = {}\n'),
        ("        seen: set[str] = set()\n",
         '        roles["unk"] = len(vocab)\n        vocab.append("<unk>")\n        seen: set[str] = set()\n')),
    sem("s03", C, "pitfall-3", "an unseen character raises KeyError",
        ("        ids = [self._ids.get(ch, self.unk_id) for ch in text]\n",
         "        ids = [self._ids[ch] for ch in text]\n")),
    sem("s04", C, "skip-unk", "skip_special keeps <unk>",
        ("        special = set(self.roles.values())\n",
         "        special = set(self.roles.values()) - {self.unk_id}\n")),
    sem("s05", C, "bos-position", "bos appended at the end",
        ('                ids.insert(0, self.roles["bos"])\n',
         '                ids.append(self.roles["bos"])\n')),
    sem("s06", C, "pitfall-1", "encode normalizes to NFC",
        ("        ids = [self._ids.get(ch, self.unk_id) for ch in text]\n",
         "        import unicodedata\n\n        ids = [self._ids.get(ch, self.unk_id) for ch in unicodedata.normalize(\"NFC\", text)]\n")),
    sem("s07", C, "tidy-decode", "decode strips surrounding white space",
        ('        return "".join(out)\n', '        return "".join(out).strip()\n')),
    sem("s08", C, "pitfall-5", "special texts matched in the input",
        ("        ids = [self._ids.get(ch, self.unk_id) for ch in text]\n",
         "        ids = []\n        i = 0\n        while i < len(text):\n"
         "            hit = next((s for s in self.special_ids if text.startswith(s, i)), None)\n"
         "            if hit is not None:\n                ids.append(self.special_ids[hit])\n                i += len(hit)\n"
         "            else:\n                ids.append(self._ids.get(text[i], self.unk_id))\n                i += 1\n")),
    sem("s09", B, "pitfall-4", "negative ids accepted (Python indexing wraps)",
        ("        if not 0 <= v < vocab_size:\n", "        if not v < vocab_size:\n")),
    sem("s10", C, "file-roles", "specials saved as text -> id, not role -> id",
        ('        doc = {"type": "char", "vocab": self.vocab, "specials": self.roles}\n',
         '        doc = {"type": "char", "vocab": self.vocab, "specials": self.special_ids}\n')),
    sem("s11", C, "pitfall-6a", "multi-character vocab entries accepted",
        ("            if t not in special_texts and len(t) != 1:\n",
         "            if t not in special_texts and len(t) == 0:\n")),
    sem("s12", C, "pitfall-6b", "any role name accepted",
        ("            if role not in ROLES:\n                raise ValueError(f\"special role {role!r} is not one of {ROLES}\")\n", "")),
    sem("s13", C, "dedupe", "a repeated special appended twice",
        ("            if role not in roles:\n                roles[role] = len(vocab)\n                vocab.append(s)\n",
         "            roles[role] = len(vocab)\n            vocab.append(s)\n")),
    sem("s14", B, "protocol", "ByteTokenizer has no unk_id attribute",
        ("        self.unk_id: Optional[int] = None\n        self._b2u", "        self._b2u")),
    sem("s15", B, "replacement", "bytes decoded with errors=ignore",
        ('        return bytes(check_ids(ids, 256)).decode("utf-8", "replace")\n',
         '        return bytes(check_ids(ids, 256)).decode("utf-8", "ignore")\n')),
    sem("s16", B, "byte-map", "byte token strings are chr(i)",
        ("        return self._b2u[v]\n", "        return chr(v)\n")),
    sem("s17", B, "latin-1", "bytes decoded as Latin-1",
        ('        return bytes(check_ids(ids, 256)).decode("utf-8", "replace")\n',
         '        return bytes(check_ids(ids, 256)).decode("latin-1")\n')),
    auto("m01", B, "stmt_delete", "a type check deleted in check_ids", "bools accepted as ids",
         ("        if isinstance(i, bool) or not hasattr(i, \"__index__\"):\n",
          "        if not hasattr(i, \"__index__\"):\n")),
    auto("m02", B, "boundary", "upper bound changed in check_ids", "< to <=",
         ("        if not 0 <= v < vocab_size:\n", "        if not 0 <= v <= vocab_size:\n")),
]

SPECS = {"L1.1": L1_1}

P = "python/tinyllm/tok/pretok.py"
BP = "python/tinyllm/tok/bpe.py"

L1_2 = [
    sem("s01", BP, "tie-break", "count ties go to the largest pair ids",
        ("                heap.append([-pair_counts[pair], pair[0], pair[1], seq, pos])\n",
         "                heap.append([-pair_counts[pair], -pair[0], -pair[1], seq, pos])\n"),
        ("            pair = (top[1], top[2])\n", "            pair = (-top[1], -top[2])\n"),
        ("                    heapq.heappush(heap, [-pair_counts[p], p[0], p[1], seq, pos])\n",
         "                    heapq.heappush(heap, [-pair_counts[p], -p[0], -p[1], seq, pos])\n")),
    sem("s02", BP, "word-weights", "initial pair counts ignore how often each word occurs",
        ("                pair_counts[pair] = pair_counts.get(pair, 0) + counts[wi]\n",
         "                pair_counts[pair] = pair_counts.get(pair, 0) + 1\n")),
    sem("s03", BP, "pitfall-1a", "encode merges the leftmost ranked pair, not the lowest rank",
        ("                if r is not None and (best_rank is None or r < best_rank):\n",
         "                if r is not None and best_rank is None:\n")),
    sem("s04", BP, "pitfall-1b", "rank ties go to the rightmost pair",
        ("                if r is not None and (best_rank is None or r < best_rank):\n",
         "                if r is not None and (best_rank is None or r <= best_rank):\n")),
    sem("s05", BP, "boundaries", "training merges across pre-token boundaries",
        ("                    for p in pretokenize_gpt2(seg):\n                        wc[",
         "                    for p in [seg]:\n                        wc[")),
    sem("s06", BP, "pitfall-5", "special tokens are trained on as text",
        ("                if sid is None:\n                    for p in pretokenize_gpt2(seg):",
         "                if True:\n                    for p in pretokenize_gpt2(seg):")),
    sem("s07", P, "pitfall-2a", "white space is str.isspace (U+001C counts)",
        ("    return ch in WHITE_SPACE\n", "    return ch.isspace()\n")),
    sem("s08", P, "pitfall-2b", "a white-space run before a word is taken whole",
        ("        if end < n and end - i >= 2:\n            end -= 1\n", "")),
    sem("s09", P, "contractions", "contractions matched case-insensitively",
        ("            suf = next((s for s in CONTRACTIONS if text.startswith(s, i + 1)), None)\n",
         "            suf = next((s for s in CONTRACTIONS if text[i + 1 : i + 1 + len(s)].lower() == s), None)\n")),
    sem("s10", P, "leading-space", "any white space may lead a word, not only U+0020",
        ('        j = i + 1 if ch == " " and i + 1 < n else i\n',
         "        j = i + 1 if is_space(ch) and i + 1 < n else i\n")),
    sem("s11", BP, "pitfall-4", "the declared Digits step is skipped",
        ('                    nxt += split_digits(p, bool(step.get("individual_digits", False)))\n',
         "                    nxt += [p]\n")),
    sem("s12", BP, "byte-map", "pre-token bytes read as Latin-1 instead of the byte map",
        ('                ids += self._bpe("".join(self._b2u[b] for b in p.encode("utf-8")))\n',
         '                ids += self._bpe(p.encode("utf-8").decode("latin-1"))\n')),
    sem("s13", BP, "gpt2-eot", "from_gpt2 leaves <|endoftext|> as plain text",
        ("        added = [(GPT2_EOT, vocab[GPT2_EOT], True)] if GPT2_EOT in vocab else []\n",
         "        added = []\n")),
    sem("s14", BP, "added-first", "added tokens are not split out before pre-tokenizing",
        ("        segs = _split_added(self._trie, text) if self.added else [(text, None)]\n",
         "        segs = [(text, None)]\n")),
    sem("s15", BP, "pitfall-6", "a byte symbol missing from the vocab is an error",
        ("        syms = [c for c in word if c in self.vocab]\n", "        syms = list(word)\n")),
    sem("s16", BP, "pitfall-3", "decode turns each token into text on its own",
        ("                buf += bytes(self._u2b[c] for c in self._id_to_tok[i])\n",
         '                buf += bytes(self._u2b[c] for c in self._id_to_tok[i]).decode("utf-8", "replace").encode("utf-8")\n')),
    sem("s17", BP, "skip-special", "skip_special ignored",
        ("                if not (skip_special and content in self.special_ids):\n", "                if True:\n")),
    sem("s18", BP, "save-added", "save drops the added tokens",
        ('            "added_tokens": added,\n', '            "added_tokens": [],\n')),
    sem("s19", BP, "pitfall-4b", "a normalizer is ignored instead of refused",
        ('        if doc.get("normalizer") is not None:\n            raise ValueError("normalizer: a byte-level BPE file has none (null)")\n', "")),
    sem("s20", BP, "batch", "encode_batch skips empty texts",
        ("        return [self.encode(t) for t in texts]\n", "        return [self.encode(t) for t in texts if t]\n")),
    sem("s21", BP, "contiguous", "a gap in the ids is accepted",
        ('        if missing:\n            raise ValueError(f"ids must be contiguous: no token for id {missing[0]}")\n', "")),
    sem("s22", P, "digits", "individual and contiguous digits swapped",
        ("            if not individual:\n", "            if individual:\n")),
    auto("m01", BP, "cmp_flip", "comparison changed in the min_freq stop", "< to <=",
         ("            if cur < 1 or cur < min_freq:\n", "            if cur < 1 or cur <= min_freq:\n")),
    auto("m02", BP, "boundary", "argument check changed in train", "min_freq < 1 to < 0",
         ("        if min_freq < 1:\n", "        if min_freq < 0:\n")),
    auto("m03", P, "const_replace", "a category dropped from is_number", "No removed",
         ('    return unicodedata.category(ch) in ("Nd", "Nl", "No")\n',
          '    return unicodedata.category(ch) in ("Nd", "Nl")\n')),
]

SPECS["L1.2"] = L1_2

W = "python/tinyllm/tok/wordpiece.py"

L1_3 = [
    sem("s01", W, "pitfall-1", "a word with no full segmentation keeps its pieces plus [UNK]",
        ("                return [self.unk_id]\n            ids.append(v)\n",
         "                return ids + [self.unk_id]\n            ids.append(v)\n")),
    sem("s02", W, "pitfall-2", "shortest match instead of longest",
        ("            n, v = trie.longest_prefix(word, start)\n",
         "            n, v = next(trie.prefixes(word, start), (0, None))\n")),
    sem("s03", W, "prefix", "continuations looked up without the ## prefix",
        ("            trie = self._word if start == 0 else self._cont\n", "            trie = self._word\n")),
    sem("s04", W, "max-len", "a word of exactly max_input_chars_per_word is [UNK]",
        ("        if len(word) > self.max_input_chars_per_word:\n", "        if len(word) >= self.max_input_chars_per_word:\n")),
    sem("s05", W, "clean-order", "white space tested before control characters",
        ('            if o == 0 or o == 0xFFFD or is_bert_control(ch):\n                continue\n            if is_bert_whitespace(ch):\n                out.append(" ")\n',
         '            if is_bert_whitespace(ch):\n                out.append(" ")\n            elif o == 0 or o == 0xFFFD or is_bert_control(ch):\n                continue\n')),
    sem("s06", W, "pitfall-3", "accents stripped only when strip_accents is True",
        ("        strip = self.strip_accents if self.strip_accents is not None else self.lowercase\n",
         "        strip = bool(self.strip_accents)\n")),
    sem("s07", W, "marks", "every mark category stripped, not only Mn",
        ('if unicodedata.category(c) != "Mn")', 'if not unicodedata.category(c).startswith("M"))')),
    sem("s08", W, "ascii-punct", "ASCII symbols ($ + ^) not treated as punctuation",
        ("    if 33 <= o <= 47 or 58 <= o <= 64 or 91 <= o <= 96 or 123 <= o <= 126:\n        return True\n", "")),
    sem("s09", W, "pitfall-4", "str.lower() on the whole string (final sigma)",
        ('            s = "".join(c.lower() for c in s)\n', "            s = s.lower()\n")),
    sem("s10", W, "specials-case", "special tokens matched case-insensitively",
        ("            n, v = self._special_trie.longest_prefix(text, i)\n",
         "            n, v = self._special_trie.longest_prefix(text.upper(), i)\n")),
    sem("s11", W, "template", "[CLS] and [SEP] swapped",
        ('            ids = [self.vocab["[CLS]"]] + ids + [self.vocab["[SEP]"]]\n',
         '            ids = [self.vocab["[SEP]"]] + ids + [self.vocab["[CLS]"]]\n')),
    sem("s12", W, "cleanup", "decode without the cleanup replacements",
        ("                t = t.replace(dirty, clean)\n", "                pass\n")),
    sem("s13", W, "glue", "## pieces decoded with a space before them",
        ("                t = t[len(self.prefix) :] if t.startswith(self.prefix) else \" \" + t\n",
         "                t = \" \" + t[len(self.prefix) :] if t.startswith(self.prefix) else \" \" + t\n")),
    sem("s14", W, "line-ids", "vocab.txt ids counted from 1",
        ("                vocab[tok] = len(vocab)\n", "                vocab[tok] = len(vocab) + 1\n")),
    sem("s15", W, "save-case", "save always writes lowercase true",
        ('                           "strip_accents": self.strip_accents, "lowercase": self.lowercase},\n',
         '                           "strip_accents": self.strip_accents, "lowercase": True},\n')),
    sem("s16", W, "cjk", "CJK ideographs not spaced",
        ('                out.append(" " + ch + " ")\n', "                out.append(ch)\n")),
    auto("m01", W, "stmt_delete", "a constructor check deleted", "missing [UNK] accepted",
         ('        if unk_token not in self.vocab:\n            raise ValueError(f"unk_token {unk_token!r} is not in the vocab")\n', "")),
    auto("m02", W, "cmp_flip", "comparison changed in the id gap check", "!= to >",
         ("        if len(self._id_to_tok) != n:\n", "        if len(self._id_to_tok) > n:\n")),
]

SPECS["L1.3"] = L1_3

U = "python/tinyllm/tok/unigram.py"
SP28 = " " * 28

L1_4 = [
    sem("s01", U, "pitfall-2", "Viterbi ties keep the last candidate (>=)",
        ("                if back[j] is None or cand > best[j]:\n", "                if back[j] is None or cand >= best[j]:\n")),
    sem("s02", U, "fuse", "adjacent unknowns not fused",
        ("            if pid == self.unk_id and ids and ids[-1] == self.unk_id:\n                continue\n", "")),
    sem("s03", U, "pitfall-3", "an unknown character scores min_score, no penalty",
        ("        unk = (self.min_score - UNK_PENALTY) * scale\n", "        unk = self.min_score * scale\n")),
    sem("s04", U, "alpha", "sample_encode ignores alpha",
        ("                edges = self._edges(w, alpha)\n", "                edges = self._edges(w)\n")),
    sem("s05", U, "pitfall-4", "backward sampling forgets the prefix mass fwd[i]",
        ("                    cands = [(i, pid, fwd[i] + s - fwd[j]) for i, pid, s in edges[j]]\n",
         "                    cands = [(i, pid, s - fwd[j]) for i, pid, s in edges[j]]\n")),
    sem("s07", U, "word-counts", "E-step ignores how often each word occurs",
        ("                        counts[self.pieces[pid][0]] += c * math.exp(fwd[i] + s + bwd[j] - z)\n",
         "                        counts[self.pieces[pid][0]] += math.exp(fwd[i] + s + bwd[j] - z)\n")),
    sem("s08", U, "pitfall-1", "backward pass takes the max (hard EM), not the sum",
        ("                    bwd[i] = _logsumexp([bwd[i], s + bwd[j]])\n",
         "                    bwd[i] = max(bwd[i], s + bwd[j])\n")),
    sem("s09", U, "prepend", "▁ prepended even when the text starts with one",
        ("    if not s.startswith(SPACE):\n        s = SPACE + s\n", "    s = SPACE + s\n")),
    sem("s10", U, "split", "words split after ▁ instead of before it",
        ("            words.append(s[start:i])\n            start = i\n",
         "            words.append(s[start : i + 1])\n            start = i + 1\n")),
    sem("s11", U, "pitfall-5", "characters can be pruned",
        ("            optional = sorted((p for p in model if p not in chars), key=lambda p: (-loss.get(p, 0.0), p))\n"
         "            kept = set(chars) | set(optional[: keep - len(chars)])\n",
         "            optional = sorted(model, key=lambda p: (-loss.get(p, 0.0), p))\n"
         "            kept = set(optional[:keep])\n")),
    sem("s12", U, "order", "final pieces sorted by string, not by score",
        ("        ordered = sorted(model.items(), key=lambda kv: (-kv[1], kv[0]))\n",
         "        ordered = sorted(model.items())\n")),
    sem("s14", U, "m-step", "M-step does not divide by the total",
        ("    return {p: math.log(c / total) for p, c in counts.items()}\n",
         "    return {p: math.log(c) for p, c in counts.items()}\n")),
    sem("s16", U, "decode-space", "decode keeps the prepended space",
        ('            if not out and t.startswith(" "):\n                t = t[1:]\n', "")),
    sem("s17", U, "unk-text", "<unk> typed in the text is not matched as the special",
        ("        for s, i in self.special_ids.items():\n            self._special_trie.insert(s, i)\n",
         "        for s, i in self.special_ids.items():\n            if i != unk_id:\n                self._special_trie.insert(s, i)\n")),
    sem("s18", U, "byte-fallback", "byte_fallback true accepted",
        ('        if model.get("byte_fallback"):\n            raise ValueError("model.byte_fallback must be false")\n', "")),
    sem("s19", U, "pitfall-1b", "log_likelihood scores the Viterbi path only",
        ("\n" + SP28 + "fwd[j] = _logsumexp([fwd[i] + s for i, _, s in edges[j]])\n",
         "\n" + SP28 + "fwd[j] = max(fwd[i] + s for i, _, s in edges[j])\n")),
    sem("s20", U, "alpha-check", "negative alpha accepted",
        ('        if not alpha >= 0:\n            raise ValueError(f"alpha must be >= 0, got {alpha}")\n', "")),
    sem("s21", U, "draw-order", "one uniform per word, reused for every piece",
        ("                path = []\n                j = n\n                while j > 0:\n                    cands",
         "                path = []\n                j = n\n                u = rng.uniform()\n                while j > 0:\n                    cands"),
        ("                    u = rng.uniform()\n", "")),
    sem("s23", U, "save-scheme", "save writes prepend_scheme first",
        ('        meta = {"type": "Metaspace", "replacement": SPACE, "prepend_scheme": "always", "split": True}\n',
         '        meta = {"type": "Metaspace", "replacement": SPACE, "prepend_scheme": "first", "split": True}\n')),
    auto("m01", U, "boundary", "unk_id bound changed", "< to <=",
         ("        if not 0 <= unk_id < len(self.pieces):\n", "        if not 0 <= unk_id <= len(self.pieces):\n")),
    auto("m02", U, "stmt_delete", "a constructor check deleted", "duplicate pieces accepted",
         ('        if len(set(texts)) != len(texts):\n            raise ValueError("pieces must be unique")\n', "")),
]

SPECS["L1.4"] = L1_4
