//! L10.9 course tests: tool calls and constrained decoding in the engine
//! (tl-engine constrain, tl-serve tools).
//!
//! Annotated exemplars (DESIGN 5.12). The Rust automaton is held to your
//! Python L8.7 on shared inputs: course/fixtures/L10.9/constrain_golden.json
//! (course/oracle/L10.9/constrain_golden.py, from the Python reference)
//! records, per schema and pattern, the regex, the canonical DFA, and the
//! masks along seeded paths through a byte-token vocabulary; L8.7's own
//! golden file (an independent Brzozowski-derivative oracle) is replayed too.
//! Generated outputs are parsed and checked against their schemas with the
//! small JSON reader and validator below, never with yours.

use std::path::PathBuf;
use std::sync::Arc;

use tl_engine::constrain::{self, Constraint, Json, TokenIndex, DEAD};
use tl_engine::sample::{Pcg32, SamplingParams};
use tl_serve::tools::{self, ResponseFormat, ToolChoice, ToolEvent, ToolParser};

fn fixtures() -> PathBuf {
    PathBuf::from(std::env::var("TINYLLM_FIXTURES").expect("TINYLLM_FIXTURES is set by ss"))
}

fn load(rel: &str) -> j::V {
    j::parse(&std::fs::read_to_string(fixtures().join(rel)).unwrap_or_else(|e| panic!("{rel}: {e}")))
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

fn vocab_of(v: &j::V) -> Vec<Option<Vec<u8>>> {
    v.arr().iter().map(|t| match t {
        j::V::Null => None,
        t => Some(unhex(t.str())),
    }).collect()
}

/// The DFA as the fixture stores it: per state, runs [lo, hi, target].
fn dfa_runs(d: &constrain::Dfa) -> Vec<Vec<[i64; 3]>> {
    (0..d.n_states)
        .map(|s| {
            let row = &d.trans[s * 256..(s + 1) * 256];
            let mut out = Vec::new();
            let mut lo = 0;
            for b in 1..=256 {
                if b == 256 || row[b] != row[lo] {
                    out.push([lo as i64, b as i64 - 1, row[lo] as i64]);
                    lo = b;
                }
            }
            out
        })
        .collect()
}

fn fixture_runs(v: &j::V) -> Vec<Vec<[i64; 3]>> {
    v.arr().iter().map(|row| row.arr().iter().map(|r| {
        let a = r.arr();
        [a[0].i64(), a[1].i64(), a[2].i64()]
    }).collect()).collect()
}

/// Replays recorded paths: at every step the allowed ids and completeness
/// must equal the record, then the recorded token is taken.
fn replay(name: &str, index: &Arc<TokenIndex>, paths: &j::V, eos: u32) {
    for (pi, path) in paths.arr().iter().enumerate() {
        let mut c = Constraint::new(Arc::clone(index));
        for (si, step) in path.arr().iter().enumerate() {
            let want: Vec<u32> = step.get("mask").arr().iter().map(|x| x.i64() as u32).collect();
            let got: Vec<u32> = c.mask().iter().enumerate().filter(|(_, &m)| m).map(|(i, _)| i as u32).collect();
            assert_eq!(got, want, "{name} path {pi} step {si}: allowed tokens");
            assert_eq!(c.is_complete(), step.get("complete").bool(), "{name} path {pi} step {si}: complete");
            if *step.get("token") == j::V::Null {
                assert!(want.is_empty(), "{name}: a path stops only where nothing is allowed");
                break;
            }
            let tok = step.get("token").i64() as u32;
            c.advance(tok).unwrap_or_else(|e| panic!("{name} path {pi} step {si}: {e}"));
            if tok == eos {
                assert!(c.done && c.mask().iter().all(|&m| !m), "{name}: after EOS nothing is allowed");
            }
        }
    }
}

/// xorshift64*: test data only, independent of the code under test.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545F4914F6CDD1D)
    }
    fn unit(&mut self) -> f32 {
        (self.next() >> 40) as f32 / (1u64 << 24) as f32
    }
}

/// A random walk under a constraint: random logits (structural bytes and
/// EOS favored so walks end), sampled with constrained_sample. Returns the
/// generated bytes, or None when the walk did not finish in `max` steps.
fn walk(index: &Arc<TokenIndex>, vocab: &[Option<Vec<u8>>], eos: u32, seed: u64, max: usize) -> Option<Vec<u8>> {
    let mut rng = Rng(seed.wrapping_mul(0x9E3779B97F4A7C15) | 1);
    let mut c = Constraint::new(Arc::clone(index));
    let mut pcg = Pcg32::new(seed, 54);
    let mut out = Vec::new();
    let p = SamplingParams::default();
    for _ in 0..max {
        let logits: Vec<f32> = (0..vocab.len())
            .map(|i| {
                let base = rng.unit() * 2.0;
                match vocab[i].as_deref() {
                    _ if i as u32 == eos => base + 8.0,
                    Some(b"\"") | Some(b"}") | Some(b"]") | Some(b",") => base + 2.5,
                    _ => base,
                }
            })
            .collect();
        let (tok, lp) = constrain::constrained_sample(&logits, &mut c, &p, &[], &[], &mut pcg).expect("a live state always allows a token");
        assert!(lp.is_finite() && lp <= 0.0, "logprob {lp}");
        if tok == eos {
            return Some(out);
        }
        out.extend_from_slice(vocab[tok as usize].as_ref().unwrap());
    }
    None
}

// ---------------------------------------------------------------------------
// the automaton

#[test]
fn hand_example_dfa() {
    // WHY: the chapter's worked automaton for (cat|car|dog)s?. Breadth-first
    //      from state 0 with bytes in order: c -> 1, d -> 2; from 1, a -> 3;
    //      from 2, o -> 4; "car", "cat", and "dog" all reach the same
    //      accepting state 5 (minimization merges them); s -> 6. Seven states,
    //      accepting {5, 6}; every other byte is DEAD.
    // KIND: unit
    // CATCHES: m01, m05
    // CHAPTER: L10.9 section 3
    let d = constrain::regex_to_dfa("(cat|car|dog)s?").unwrap();
    assert_eq!(d.n_states, 7);
    assert_eq!(d.accept, vec![false, false, false, false, false, true, true]);
    let t = |s: usize, b: u8| d.trans[s * 256 + b as usize];
    assert_eq!((t(0, b'c'), t(0, b'd'), t(1, b'a'), t(2, b'o')), (1, 2, 3, 4));
    assert_eq!((t(3, b't'), t(3, b'r'), t(4, b'g'), t(5, b's')), (5, 5, 5, 6));
    assert_eq!(d.trans.iter().filter(|&&x| x != DEAD).count(), 8, "only the 8 edges above are live");
    assert!(d.matches(b"cats") && d.matches(b"dog") && !d.matches(b"ca") && !d.matches(b"dogss"));
    assert_eq!(d.step(0, b"cax").unwrap(), DEAD);
    assert_eq!(d.step(DEAD, b"c").unwrap(), DEAD);
    assert!(d.step(7, b"c").is_err());
}

#[test]
fn dfa_matches_python_l8_7() {
    // WHY: the DFA is canonical (dead states gone, minimized, numbered
    //      breadth-first over bytes 0..255), so the Rust port and your Python
    //      L8.7 must produce IDENTICAL transition tables for the same pattern,
    //      and the same regex text for the same schema (property order, enum
    //      escaping, array bounds, optional members). 12 schemas, 8 patterns.
    // KIND: differential
    // CATCHES: s02, s03, s04, s05, m02, m03, m04
    // CHAPTER: L10.9 section 2
    let g = load("L10.9/constrain_golden.json");
    for c in g.get("schemas").arr() {
        let name = c.get("name").str();
        let schema = Json::parse(c.get("schema").str()).unwrap();
        let pat = constrain::json_schema_to_regex(&schema).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(pat, c.get("regex").str(), "{name}: regex text");
    }
    for c in g.get("schemas").arr().iter().chain(g.get("regexes").arr()) {
        let name = c.get("name").str();
        let pat = match c.get_opt("pattern") {
            Some(p) => p.str().to_string(),
            None => c.get("regex").str().to_string(),
        };
        let d = constrain::regex_to_dfa(&pat).unwrap_or_else(|e| panic!("{name}: {e}"));
        let want = c.get("dfa");
        assert_eq!(d.n_states as i64, want.get("n_states").i64(), "{name}: states");
        let acc: Vec<bool> = want.get("accept").arr().iter().map(|x| x.bool()).collect();
        assert_eq!(d.accept, acc, "{name}: accepting states");
        assert_eq!(dfa_runs(&d), fixture_runs(want.get("trans")), "{name}: transitions");
    }
}

#[test]
fn masks_match_python_l8_7() {
    // WHY: what the sampler sees: at every step of seeded paths the set of
    //      allowed token ids (a token is allowed iff walking ALL its bytes
    //      stays live; multi-byte and UTF-8 tokens included), EOS exactly in
    //      accepting states, specials and empty tokens never. Both the Python
    //      reference's paths (L10.9 golden) and L8.7's independent oracle.
    // KIND: differential
    // CATCHES: s02, s10, m04, m10
    // CHAPTER: L10.9 section 2
    let g = load("L10.9/constrain_golden.json");
    let vocab = vocab_of(g.get("vocab"));
    let eos = g.get("eos_id").i64() as u32;
    for c in g.get("schemas").arr().iter().chain(g.get("regexes").arr()) {
        let name = c.get("name").str();
        let pat = c.get_opt("pattern").map(|p| p.str().to_string()).unwrap_or_else(|| c.get("regex").str().to_string());
        let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa(&pat).unwrap(), &vocab, Some(eos)).unwrap());
        replay(name, &idx, c.get("paths"), eos);
    }
    let old = load("L8.7/masks_golden.json");
    for c in old.get("cases").arr() {
        let vocab = vocab_of(c.get("vocab"));
        let eos = c.get("eos_id").i64() as u32;
        let pat = match c.get_opt("pattern") {
            Some(p) => p.str().to_string(),
            None => constrain::json_schema_to_regex(&Json::parse(&j::dump(c.get("schema"))).unwrap()).unwrap(),
        };
        let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa(&pat).unwrap(), &vocab, Some(eos)).unwrap());
        replay(c.get("name").str(), &idx, c.get("paths"), eos);
    }
}

#[test]
fn subset_errors_are_refused() {
    // WHY: a pattern or schema outside the subset must be an error at
    //      request time (the server answers 422), never a silently different
    //      language: anchors, lazy quantifiers, lookarounds, backreferences,
    //      non-ASCII, unbalanced groups, out-of-range repeats, an empty
    //      language; schema keywords like pattern, minLength, $ref.
    // KIND: boundary
    // CATCHES: s08, m08
    // CHAPTER: L10.9 section 5, Pitfalls
    let g = load("L10.9/constrain_golden.json");
    for p in g.get("bad_regexes").arr() {
        assert!(constrain::regex_to_dfa(p.str()).is_err(), "pattern {:?} must be refused", p.str());
    }
    for s in g.get("bad_schemas").arr() {
        let schema = Json::parse(s.str()).unwrap();
        assert!(constrain::json_schema_to_regex(&schema).is_err(), "schema {} must be refused", s.str());
    }
}

#[test]
fn dumps_matches_python() {
    // WHY: enum and const values are matched as the bytes Python's
    //      json.dumps(v, separators=(",", ":"), ensure_ascii=False) writes:
    //      key order kept, -0 as 0, floats in repr (1e+16, 1.5e-05,
    //      100000.0), escapes \" \\ \n and \u0001, non-ASCII raw. One
    //      different byte and the model can never produce the allowed value.
    // KIND: unit
    // CATCHES: s09, m09
    // CHAPTER: L10.9 section 5, Pitfalls
    let g = load("L10.9/constrain_golden.json");
    for c in g.get("dumps").arr() {
        let v = Json::parse(c.get("text").str()).unwrap_or_else(|e| panic!("{}: {e}", c.get("text").str()));
        assert_eq!(v.dumps(), c.get("compact").str(), "dumps of {}", c.get("text").str());
    }
    assert!(Json::parse("{\"a\":1,}").is_err() && Json::parse("01").is_err() && Json::parse("[1] x").is_err());
}

#[test]
fn token_index_rules() {
    // WHY: the mask's edge cases: a special token (None) and the empty token
    //      are never allowed; EOS only where the prefix is a whole string and
    //      it keeps the state; a forbidden token or anything after EOS is an
    //      error, not a silent state change.
    // KIND: boundary
    // CATCHES: s06, m07, m10
    // CHAPTER: L10.9 section 4
    let vocab: Vec<Option<Vec<u8>>> = vec![Some(b"a".to_vec()), Some(b"ab".to_vec()), None, Some(Vec::new()), Some(b"b".to_vec()), None];
    let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa("ab?").unwrap(), &vocab, Some(5)).unwrap());
    assert_eq!(idx.mask(0).unwrap(), vec![true, true, false, false, false, false]);
    let s1 = idx.next_state(0, 0).unwrap();
    assert_eq!(idx.mask(s1).unwrap(), vec![false, false, false, false, true, true], "after 'a': 'b' or EOS");
    assert_eq!(idx.next_state(s1, 5).unwrap(), s1, "EOS keeps the state");
    assert_eq!(idx.next_state(0, 5).unwrap(), DEAD, "EOS before a whole string is DEAD");
    assert_eq!(idx.next_state(0, 2).unwrap(), DEAD, "a special is DEAD");
    assert!(idx.next_state(0, 6).is_err() && idx.mask(99).is_err());
    assert!(TokenIndex::new(constrain::regex_to_dfa("a").unwrap(), &vocab, Some(6)).is_err());
    let mut c = Constraint::new(Arc::clone(&idx));
    assert!(c.advance(4).is_err(), "'b' first is forbidden");
    c.advance(0).unwrap();
    assert!(c.is_complete());
    c.advance(5).unwrap();
    assert!(c.done && c.advance(4).is_err());
}

#[test]
fn constrained_sample_hand_example() {
    // WHY: the mask comes before the sampler, and the logprob is the masked
    //      distribution's. Pattern ab?, vocabulary [a b c EOS], logits
    //      [0 1 5 2]: in state 0 only a is allowed, so greedy takes a (not
    //      the larger c) with logprob 0; then b or EOS: greedy takes EOS
    //      (2 > 1) with logprob 2 - ln(e^1 + e^2).
    // KIND: unit
    // CATCHES: s07, s11, m06, m11
    // CHAPTER: L10.9 section 3
    let vocab = vec![Some(b"a".to_vec()), Some(b"b".to_vec()), Some(b"c".to_vec()), None];
    let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa("ab?").unwrap(), &vocab, Some(3)).unwrap());
    let mut c = Constraint::new(idx);
    let mut rng = Pcg32::new(0, 54);
    let logits = [0.0f32, 1.0, 5.0, 2.0];
    let (t, lp) = constrain::constrained_sample(&logits, &mut c, &SamplingParams::greedy(), &[], &[], &mut rng).unwrap();
    assert_eq!((t, lp), (0, 0.0));
    let (t, lp) = constrain::constrained_sample(&logits, &mut c, &SamplingParams::greedy(), &[], &[], &mut rng).unwrap();
    assert_eq!(t, 3);
    assert!((lp - (2.0 - (1f64.exp() + 2f64.exp()).ln())).abs() < 1e-12, "logprob {lp}");
    assert!(constrain::apply_mask(&logits, &[false; 4]).is_err(), "a mask that allows nothing is an error");
}

#[test]
fn constrained_output_always_parses() {
    // WHY: the point of constraining: whatever the logits, the finished
    //      output is valid JSON that satisfies the schema. 25 seeded random
    //      walks per fixture schema through the byte-token vocabulary, each
    //      parsed and validated by the test's own JSON reader and validator.
    // KIND: property
    // CATCHES: s03, s04, s05, s06, m02
    // CHAPTER: L10.9 section 2
    let g = load("L10.9/constrain_golden.json");
    let vocab = vocab_of(g.get("vocab"));
    let eos = g.get("eos_id").i64() as u32;
    for c in g.get("schemas").arr() {
        let name = c.get("name").str();
        let schema = j::parse(c.get("schema").str());
        let pat = constrain::json_schema_to_regex(&Json::parse(c.get("schema").str()).unwrap()).unwrap();
        let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa(&pat).unwrap(), &vocab, Some(eos)).unwrap());
        for seed in 0..25u64 {
            let out = walk(&idx, &vocab, eos, seed, 600).unwrap_or_else(|| panic!("{name} seed {seed}: no EOS in 600 steps"));
            let text = String::from_utf8(out.clone()).unwrap_or_else(|_| panic!("{name} seed {seed}: not UTF-8: {out:?}"));
            let v = j::try_parse(&text).unwrap_or_else(|e| panic!("{name} seed {seed}: {text:?} is not JSON: {e}"));
            if let Err(e) = j::validate(&v, &schema) {
                panic!("{name} seed {seed}: {text} breaks the schema: {e}");
            }
        }
    }
}

#[test]
fn json_object_grammar() {
    // WHY: response_format json_object asks for any JSON object, which no
    //      regular language describes exactly; the grammar bounds the
    //      nesting (3 levels). It accepts objects up to that depth and
    //      rejects arrays, scalars, and broken objects.
    // KIND: boundary
    // CATCHES: s01, m01, m05, m12
    // CHAPTER: L10.9 section 4
    let d = constrain::regex_to_dfa(&constrain::json_object_regex(3)).unwrap();
    for ok in [&b"{}"[..], br#"{"a":1}"#, br#"{"a":[1,{"b":null}],"c":"\u00e9"}"#, br#"{"x":{"y":{"z":true}}}"#] {
        assert!(d.matches(ok), "{} must match", String::from_utf8_lossy(ok));
    }
    for bad in [&b"[]"[..], b"1", br#"{"a":}"#, br#"{"a":1,}"#, br#"{a:1}"#, br#"{"x":{"y":{"z":{"w":1}}}}"#] {
        assert!(!d.matches(bad), "{} must not match", String::from_utf8_lossy(bad));
    }
}

// ---------------------------------------------------------------------------
// tool requests

const WEATHER: &str = r#"{"type":"function","function":{"name":"get_weather","description":"Weather for a city","parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"],"additionalProperties":false}}}"#;

fn body(extra: &str) -> String {
    format!(r#"{{"model":"m","messages":[{{"role":"user","content":"hi"}}],"tools":[{WEATHER}]{extra}}}"#)
}

#[test]
fn parse_tool_request_hand_example() {
    // WHY: the conformance suite's tool (tools.call): one function, a
    //      one-property object schema. tool_choice defaults to auto,
    //      parallel calls to true; a named choice must name a listed tool; a
    //      schema keyword outside the subset is 422 unsupported_parameter,
    //      every other mistake 400.
    // KIND: unit
    // CATCHES: s12, m13, m23
    // CHAPTER: L10.9 section 3
    let r = tools::parse_tool_request(&body("")).unwrap();
    assert_eq!((r.tools.len(), &r.tools[0].name, &r.choice, r.parallel, r.response_format), (1, &"get_weather".to_string(), &ToolChoice::Auto, true, ResponseFormat::Text));
    let r = tools::parse_tool_request(&body(r#","tool_choice":{"type":"function","function":{"name":"get_weather"}},"parallel_tool_calls":false"#)).unwrap();
    assert_eq!((r.choice, r.parallel), (ToolChoice::Named("get_weather".into()), false));
    let e = tools::parse_tool_request(&body(r#","tool_choice":{"type":"function","function":{"name":"nope"}}"#)).unwrap_err();
    assert_eq!(e.status, 400);
    let e = tools::parse_tool_request(r#"{"model":"m","messages":[],"tool_choice":"required"}"#).unwrap_err();
    assert_eq!((e.status, e.param.as_str()), (400, "tool_choice"));
    let bad = WEATHER.replace(r#"{"type":"string"}"#, r#"{"type":"string","pattern":"^[A-Z]"}"#);
    let e = tools::parse_tool_request(&format!(r#"{{"messages":[],"tools":[{bad}]}}"#)).unwrap_err();
    assert_eq!((e.status, e.code.as_deref()), (422, Some("unsupported_parameter")));
    assert!(e.message.contains("pattern"), "the message names the keyword: {}", e.message);
    let e = tools::parse_tool_request(&body(r#","response_format":{"type":"json_schema"}"#)).unwrap_err();
    assert_eq!(e.status, 422);
    let r = tools::parse_tool_request(r#"{"messages":[],"response_format":{"type":"json_object"}}"#).unwrap();
    assert_eq!((r.response_format, r.tools.len()), (ResponseFormat::JsonObject, 0));
    let dup = format!(r#"{{"messages":[],"tools":[{WEATHER},{WEATHER}]}}"#);
    assert_eq!(tools::parse_tool_request(&dup).unwrap_err().status, 400);
    let e = tools::parse_tool_request(&body("")).map(|_| ()).err();
    assert!(e.is_none());
    let j = j::parse(&tools::parse_tool_request(&body(r#","tool_choice":"sometimes""#)).unwrap_err().to_json());
    let err = j.get("error");
    assert_eq!((err.get("type").str(), err.get("param").str()), ("invalid_request_error", "tool_choice"));
    let unsup = tools::parse_tool_request(&body(r#","response_format":{"type":"json_schema"}"#)).unwrap_err().to_api_error();
    assert_eq!((unsup.status, unsup.code, unsup.param.as_deref()), (422, Some("unsupported_parameter"), Some("response_format")), "the server answers 422 with the code");
}

#[test]
fn grammar_by_tool_choice() {
    // WHY: tool_choice decides what decoding may produce: a named function
    //      constrains the whole answer to exactly one call of it; required to
    //      one or more calls (up to 4, newline-separated, unless parallel
    //      calls are off); auto leaves text free until the model writes
    //      <tool_call>; none is free text (or a JSON object with
    //      response_format json_object).
    // KIND: unit
    // CATCHES: s01, s13, m13, m14
    // CHAPTER: L10.9 section 2
    let call = r#"<tool_call>{"name":"get_weather","arguments":{"city":"Paris"}}</tool_call>"#;
    // Two tools with the same parameters: naming one must exclude the other.
    let both = format!(r#"{{"messages":[],"tools":[{WEATHER},{}],"tool_choice":{{"type":"function","function":{{"name":"get_weather"}}}}}}"#, WEATHER.replace("get_weather", "get_time"));
    let named = tools::grammar(&tools::parse_tool_request(&both).unwrap()).unwrap();
    assert_eq!(named.trigger, None);
    let d = constrain::regex_to_dfa(&named.pattern).unwrap();
    assert!(d.matches(call.as_bytes()));
    assert!(!d.matches(call.replace("get_weather", "get_time").as_bytes()));
    assert!(!d.matches(call.replace(r#""city":"Paris""#, r#""town":"Paris""#).as_bytes()), "arguments follow the schema");
    assert!(!d.matches(format!("{call}\n{call}").as_bytes()), "a named choice is one call");
    let req = tools::grammar(&tools::parse_tool_request(&body(r#","tool_choice":"required""#)).unwrap()).unwrap();
    let d = constrain::regex_to_dfa(&req.pattern).unwrap();
    assert!(d.matches(call.as_bytes()) && d.matches(format!("{call}\n{call}").as_bytes()));
    assert!(!d.matches(format!("{call}\n{call}\n{call}\n{call}\n{call}").as_bytes()), "at most 4 calls");
    assert!(!d.matches(b"Paris is sunny."));
    let single = tools::grammar(&tools::parse_tool_request(&body(r#","tool_choice":"required","parallel_tool_calls":false"#)).unwrap()).unwrap();
    assert!(!constrain::regex_to_dfa(&single.pattern).unwrap().matches(format!("{call}\n{call}").as_bytes()));
    let auto = tools::grammar(&tools::parse_tool_request(&body("")).unwrap()).unwrap();
    assert_eq!(auto.trigger.as_deref(), Some("<tool_call>"));
    assert!(constrain::regex_to_dfa(&auto.pattern).unwrap().matches(call.strip_prefix("<tool_call>").unwrap().as_bytes()));
    assert_eq!(tools::grammar(&tools::parse_tool_request(&body(r#","tool_choice":"none""#)).unwrap()), None);
    let jo = tools::grammar(&tools::parse_tool_request(r#"{"messages":[],"response_format":{"type":"json_object"}}"#).unwrap()).unwrap();
    assert!(constrain::regex_to_dfa(&jo.pattern).unwrap().matches(br#"{"a":1}"#));
}

#[test]
fn render_messages_with_tools() {
    // WHY: a small model only calls tools it was told about, in the format
    //      it was trained on: the tools go into the (first) system message;
    //      an assistant turn's tool_calls come back as <tool_call> blocks and
    //      a tool result as a <tool_response> user turn, so a multi-turn
    //      conversation renders the way it was generated.
    // KIND: unit
    // CATCHES: m15, m22
    // CHAPTER: L10.9 section 4
    let req = tools::parse_tool_request(&body("")).unwrap();
    let msgs = Json::parse(r#"[{"role":"system","content":"Be brief."},{"role":"user","content":"Weather in Paris?"},
        {"role":"assistant","content":null,"tool_calls":[{"id":"call_1","type":"function","function":{"name":"get_weather","arguments":"{\"city\":\"Paris\"}"}}]},
        {"role":"tool","tool_call_id":"call_1","content":"18C, sunny"}]"#).unwrap();
    let out = tools::render_messages(&msgs, &req.tools).unwrap();
    assert_eq!(out.len(), 4);
    assert_eq!(out[0].0, "system");
    assert!(out[0].1.starts_with("Be brief.\n\n") && out[0].1.contains(r#""name":"get_weather""#) && out[0].1.contains("<tool_call>"));
    assert_eq!(out[2], ("assistant".to_string(), r#"<tool_call>{"name":"get_weather","arguments":{"city":"Paris"}}</tool_call>"#.to_string()));
    assert_eq!(out[3], ("user".to_string(), "<tool_response>18C, sunny</tool_response>".to_string()));
    let t = tl_serve::template::Template::parse(tl_serve::template::DEFAULT_TEMPLATE).unwrap();
    let prompt = tools::render_prompt(&t, &msgs, &req.tools, "", "").unwrap();
    assert!(prompt.starts_with("<|system|>\nBe brief.\n\nYou can call functions."), "{prompt}");
    assert!(prompt.contains("<|tool|>") == false && prompt.contains("<|user|>\n<tool_response>18C, sunny</tool_response>\n"), "{prompt}");
    assert!(prompt.ends_with("<|assistant|>\n"), "the prompt ends with the generation prompt");
    let plain = tools::render_messages(&Json::parse(r#"[{"role":"user","content":"hi"}]"#).unwrap(), &req.tools).unwrap();
    assert_eq!(plain[0].0, "system", "without a system message one is added first");
    assert_eq!(tools::render_messages(&Json::parse(r#"[{"role":"user","content":"hi"}]"#).unwrap(), &[]).unwrap(), vec![("user".to_string(), "hi".to_string())]);
}

#[test]
fn vocab_bytes_marks_specials() {
    // WHY: chat markers and EOS must never be produced by a grammar: their
    //      ids map to None; every other id to its bytes.
    // KIND: unit
    // CATCHES: m16
    // CHAPTER: L10.9 section 4
    let v = tools::vocab_bytes(&tl_tok::ByteTokenizer, &[0, 255]);
    assert_eq!(v.len(), 256);
    assert_eq!((v[0].clone(), v[65].clone(), v[255].clone()), (None, Some(vec![65]), None));
}

// ---------------------------------------------------------------------------
// parsing the answer

fn feed(p: &mut ToolParser, pieces: &[&str]) -> Vec<ToolEvent> {
    let mut ev = Vec::new();
    for x in pieces {
        ev.extend(p.push(x));
    }
    ev.extend(p.finish());
    ev
}

#[test]
fn parser_hand_example() {
    // WHY: the chapter's stream. "Sure." is content; "<tool_" is held back
    //      until "call>" proves it is markup; the call starts when its header
    //      {"name":"get_weather","arguments": is complete; the arguments
    //      stream as they arrive ({"city":"Pa, then ris"}) and end at their
    //      closing brace; the closing }</tool_call> is not content.
    // KIND: unit
    // CATCHES: s14, s15, m18
    // CHAPTER: L10.9 section 3
    let mut p = ToolParser::new("req7");
    let a = p.push("Sure.<tool_");
    assert_eq!(a, vec![ToolEvent::Content("Sure.".into())], "the markup prefix is held back");
    let b = p.push(r#"call>{"name":"get_weather","argu"#);
    assert!(b.is_empty(), "no call before its header is complete: {b:?}");
    let c = p.push(r#"ments":{"city":"Pa"#);
    assert_eq!(c, vec![
        ToolEvent::CallStart { index: 0, id: "call_req7_0".into(), name: "get_weather".into() },
        ToolEvent::Arguments { index: 0, fragment: r#"{"city":"Pa"#.into() },
    ]);
    let d = p.push(r#"ris"}}</tool_call>"#);
    assert_eq!(d, vec![ToolEvent::Arguments { index: 0, fragment: r#"ris"}"#.into() }]);
    assert!(p.finish().is_empty());
    let (content, calls) = tools::collect(&[a, b, c, d].concat());
    assert_eq!(content.as_deref(), Some("Sure."));
    assert_eq!((calls[0].name.as_str(), calls[0].arguments.as_str()), ("get_weather", r#"{"city":"Paris"}"#));
    assert_eq!(tools::finish_reason(calls.len(), "stop"), "tool_calls");
    assert_eq!(tools::finish_reason(0, "length"), "length");
}

#[test]
fn parser_holds_back_only_real_markup() {
    // WHY: holding back too little leaks "<tool_call>" into the content
    //      shown to the user; holding back too much eats text. "a<b" and a
    //      lone "<" are content; an answer that ENDS with "<tool" gives it
    //      back at finish; a "<tool_call>" that is not followed by a call
    //      header is content too.
    // KIND: boundary
    // CATCHES: s15, m18
    // CHAPTER: L10.9 section 5, Pitfalls
    let text = |ev: Vec<ToolEvent>| tools::collect(&ev).0.unwrap_or_default();
    assert_eq!(text(feed(&mut ToolParser::new("r"), &["a<", "b"])), "a<b");
    assert_eq!(text(feed(&mut ToolParser::new("r"), &["x <tool"])), "x <tool");
    assert_eq!(text(feed(&mut ToolParser::new("r"), &["<tool_call>hello"])), "<tool_call>hello");
    let ev = feed(&mut ToolParser::new("r"), &["1 <", "tool_c", "all>{\"name\":\"f\",\"arguments\":{}}</tool_call> done"]);
    let (content, calls) = tools::collect(&ev);
    assert_eq!((content.as_deref(), calls.len()), (Some("1  done"), 1));
}

#[test]
fn parser_parallel_calls() {
    // WHY: parallel calls are numbered 0, 1, ... with their own ids, and the
    //      newline between them is markup, not content.
    // KIND: unit
    // CATCHES: m19, m20
    // CHAPTER: L10.9 section 4
    let two = "<tool_call>{\"name\":\"a\",\"arguments\":{\"x\":[1,{\"y\":\"}\"}]}}</tool_call>\n<tool_call>{\"name\":\"b\",\"arguments\":{}}</tool_call>";
    let (content, calls) = tools::collect(&feed(&mut ToolParser::new("q"), &[two]));
    assert_eq!(content, None);
    assert_eq!(calls.len(), 2);
    assert_eq!((calls[0].id.as_str(), calls[0].arguments.as_str()), ("call_q_0", r#"{"x":[1,{"y":"}"}]}"#));
    assert_eq!((calls[1].id.as_str(), calls[1].name.as_str(), calls[1].arguments.as_str()), ("call_q_1", "b", "{}"));
}

#[test]
fn parser_is_split_invariant() {
    // WHY: tokens cut the text anywhere (inside "<tool_call>", inside a
    //      string, between a backslash and its escape); the events folded
    //      together must not depend on where. Every 2-way split and 200
    //      seeded multi-way splits of one answer give the same content and
    //      calls as feeding it whole.
    // KIND: property
    // CATCHES: s14, m17, m19, m20
    // CHAPTER: L10.9 section 2
    let text = "Let me check. <tool_call>{\"name\":\"get_weather\",\"arguments\":{\"city\":\"Par\\\"is \u{e9}\"}}</tool_call>\n<tool_call>{\"name\":\"t\",\"arguments\":{\"a\":[]}}</tool_call>";
    let want = tools::collect(&feed(&mut ToolParser::new("s"), &[text]));
    assert_eq!(want.1.len(), 2);
    let cuts: Vec<usize> = (1..text.len()).filter(|&i| text.is_char_boundary(i)).collect();
    for &c in &cuts {
        let got = tools::collect(&feed(&mut ToolParser::new("s"), &[&text[..c], &text[c..]]));
        assert_eq!(got, want, "split at {c}");
    }
    let mut rng = Rng(7);
    for _ in 0..200 {
        let mut pts: Vec<usize> = cuts.iter().copied().filter(|_| rng.next() % 5 == 0).collect();
        pts.insert(0, 0);
        pts.push(text.len());
        let pieces: Vec<&str> = pts.windows(2).map(|w| &text[w[0]..w[1]]).collect();
        assert_eq!(tools::collect(&feed(&mut ToolParser::new("s"), &pieces)), want, "pieces {pieces:?}");
    }
}

#[test]
fn message_and_delta_json_shapes() {
    // WHY: what clients parse (openai-subset.v1.yaml, ag.01): the message has
    //      content null when there is none and tool_calls with id, type
    //      "function", name, and arguments as a JSON STRING; the first delta
    //      of a call carries index, id, type, name, and empty arguments; later
    //      deltas carry only index and an arguments fragment.
    // KIND: conformance
    // CATCHES: s16, m21
    // CHAPTER: L10.9 section 4
    let calls = vec![tools::ToolCall { id: "call_x_0".into(), name: "get_weather".into(), arguments: r#"{"city":"Paris"}"#.into() }];
    let m = j::parse(&tools::message_json(None, &calls));
    assert_eq!(m.get("role").str(), "assistant");
    assert_eq!(*m.get("content"), j::V::Null);
    let tc = &m.get("tool_calls").arr()[0];
    assert_eq!((tc.get("id").str(), tc.get("type").str()), ("call_x_0", "function"));
    assert_eq!((tc.get("function").get("name").str(), tc.get("function").get("arguments").str()), ("get_weather", r#"{"city":"Paris"}"#));
    let plain = j::parse(&tools::message_json(Some("hi \"you\""), &[]));
    assert_eq!(plain.get("content").str(), "hi \"you\"");
    assert!(plain.get_opt("tool_calls").is_none());
    let d = j::parse(&tools::delta_json(&ToolEvent::CallStart { index: 1, id: "call_x_1".into(), name: "f".into() }));
    let t = &d.get("tool_calls").arr()[0];
    assert_eq!((t.get("index").i64(), t.get("id").str(), t.get("type").str(), t.get("function").get("name").str(), t.get("function").get("arguments").str()), (1, "call_x_1", "function", "f", ""));
    let f = j::parse(&tools::delta_json(&ToolEvent::Arguments { index: 1, fragment: "{\"a\":".into() }));
    let t = &f.get("tool_calls").arr()[0];
    assert_eq!((t.get("index").i64(), t.get("function").get("arguments").str()), (1, "{\"a\":"));
    assert!(t.get_opt("id").is_none() && t.get("function").get_opt("name").is_none());
    assert_eq!(j::parse(&tools::delta_json(&ToolEvent::Content("x".into()))).get("content").str(), "x");
}

#[test]
fn forced_call_from_a_random_model_is_valid() {
    // WHY: MS-L10's PR check runs a tiny random model: with tool_choice
    //      naming the function, the constraint ALONE must guarantee a valid
    //      call. 40 seeded random walks over a byte vocabulary (plus EOS) end
    //      in exactly one call of get_weather whose arguments parse and hold
    //      a string "city" and nothing else.
    // KIND: property
    // CATCHES: s07, s11, m06, m17
    // CHAPTER: L10.9 section 2
    let req = tools::parse_tool_request(&body(r#","tool_choice":{"type":"function","function":{"name":"get_weather"}}"#)).unwrap();
    let g = tools::grammar(&req).unwrap();
    let mut vocab = tools::vocab_bytes(&tl_tok::ByteTokenizer, &[]);
    vocab.push(None);
    let eos = 256u32;
    let idx = Arc::new(TokenIndex::new(constrain::regex_to_dfa(&g.pattern).unwrap(), &vocab, Some(eos)).unwrap());
    for seed in 0..40u64 {
        let out = walk(&idx, &vocab, eos, seed, 2000).unwrap_or_else(|| panic!("seed {seed}: no EOS"));
        let text = String::from_utf8(out).unwrap();
        let (content, calls) = tools::collect(&feed(&mut ToolParser::new("f"), &[&text]));
        assert_eq!((content, calls.len()), (None, 1), "seed {seed}: {text}");
        assert_eq!(calls[0].name, "get_weather");
        let args = j::try_parse(&calls[0].arguments).unwrap_or_else(|e| panic!("seed {seed}: {e}"));
        assert_eq!(args.obj().len(), 1, "seed {seed}: {}", calls[0].arguments);
        let _ = args.get("city").str();
    }
}

/// A tiny JSON reader and a validator for the schema subset, independent of
/// the code under test. Numbers keep their text.
mod j {
    #[derive(Debug, Clone, PartialEq)]
    pub enum V {
        Null,
        Bool(bool),
        Num(String),
        Str(String),
        Arr(Vec<V>),
        Obj(Vec<(String, V)>),
    }

    impl V {
        pub fn get(&self, k: &str) -> &V {
            self.get_opt(k).unwrap_or_else(|| panic!("no key {k:?} in {self:?}"))
        }
        pub fn get_opt(&self, k: &str) -> Option<&V> {
            self.obj().iter().find(|(a, _)| a == k).map(|(_, v)| v)
        }
        pub fn obj(&self) -> &Vec<(String, V)> {
            match self {
                V::Obj(kv) => kv,
                _ => panic!("not an object: {self:?}"),
            }
        }
        pub fn str(&self) -> &str {
            match self {
                V::Str(s) => s,
                _ => panic!("not a string: {self:?}"),
            }
        }
        pub fn bool(&self) -> bool {
            match self {
                V::Bool(b) => *b,
                _ => panic!("not a bool: {self:?}"),
            }
        }
        pub fn i64(&self) -> i64 {
            match self {
                V::Num(n) => n.parse().unwrap_or_else(|_| panic!("not an integer: {n}")),
                _ => panic!("not a number: {self:?}"),
            }
        }
        pub fn arr(&self) -> &Vec<V> {
            match self {
                V::Arr(a) => a,
                _ => panic!("not an array: {self:?}"),
            }
        }
    }

    pub fn parse(s: &str) -> V {
        try_parse(s).unwrap_or_else(|e| panic!("{e}: {s:?}"))
    }

    pub fn try_parse(s: &str) -> Result<V, String> {
        let b = s.as_bytes();
        let mut i = 0;
        let v = val(b, &mut i)?;
        ws(b, &mut i);
        if i != b.len() {
            return Err(format!("trailing characters at {i}"));
        }
        Ok(v)
    }

    fn ws(b: &[u8], i: &mut usize) {
        while *i < b.len() && matches!(b[*i], b' ' | b'\n' | b'\t' | b'\r') {
            *i += 1;
        }
    }

    fn val(b: &[u8], i: &mut usize) -> Result<V, String> {
        ws(b, i);
        let c = *b.get(*i).ok_or("unexpected end")?;
        match c {
            b'{' | b'[' => {
                let close = if c == b'{' { b'}' } else { b']' };
                *i += 1;
                let mut kv = Vec::new();
                let mut a = Vec::new();
                ws(b, i);
                if b.get(*i) == Some(&close) {
                    *i += 1;
                    return Ok(if c == b'{' { V::Obj(kv) } else { V::Arr(a) });
                }
                loop {
                    if c == b'{' {
                        let V::Str(k) = val(b, i)? else { return Err("key is not a string".into()) };
                        ws(b, i);
                        if b.get(*i) != Some(&b':') {
                            return Err("':' expected".into());
                        }
                        *i += 1;
                        kv.push((k, val(b, i)?));
                    } else {
                        a.push(val(b, i)?);
                    }
                    ws(b, i);
                    match b.get(*i) {
                        Some(b',') => *i += 1,
                        Some(x) if *x == close => {
                            *i += 1;
                            return Ok(if c == b'{' { V::Obj(kv) } else { V::Arr(a) });
                        }
                        _ => return Err(format!("',' or close expected at {i}")),
                    }
                }
            }
            b'"' => {
                *i += 1;
                let mut s = Vec::new();
                loop {
                    let c = *b.get(*i).ok_or("unterminated string")?;
                    *i += 1;
                    match c {
                        b'"' => break,
                        b'\\' => {
                            let e = *b.get(*i).ok_or("bad escape")?;
                            *i += 1;
                            match e {
                                b'"' | b'\\' | b'/' => s.push(e),
                                b'b' => s.push(8),
                                b'f' => s.push(12),
                                b'n' => s.push(b'\n'),
                                b'r' => s.push(b'\r'),
                                b't' => s.push(b'\t'),
                                b'u' => {
                                    let h = std::str::from_utf8(b.get(*i..*i + 4).ok_or("short \\u")?).map_err(|_| "bad \\u")?;
                                    let cp = u32::from_str_radix(h, 16).map_err(|_| "bad \\u")?;
                                    *i += 4;
                                    let ch = char::from_u32(cp).unwrap_or('\u{FFFD}');
                                    let mut buf = [0u8; 4];
                                    s.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
                                }
                                _ => return Err("bad escape".into()),
                            }
                        }
                        c if c < 0x20 => return Err("control character in a string".into()),
                        c => s.push(c),
                    }
                }
                String::from_utf8(s).map(V::Str).map_err(|_| "string is not UTF-8".into())
            }
            b't' if b[*i..].starts_with(b"true") => {
                *i += 4;
                Ok(V::Bool(true))
            }
            b'f' if b[*i..].starts_with(b"false") => {
                *i += 5;
                Ok(V::Bool(false))
            }
            b'n' if b[*i..].starts_with(b"null") => {
                *i += 4;
                Ok(V::Null)
            }
            b'-' | b'0'..=b'9' => {
                let st = *i;
                while *i < b.len() && matches!(b[*i], b'-' | b'+' | b'.' | b'e' | b'E' | b'0'..=b'9') {
                    *i += 1;
                }
                let t = std::str::from_utf8(&b[st..*i]).unwrap().to_string();
                t.parse::<f64>().map_err(|_| format!("bad number {t}"))?;
                let digits = t.trim_start_matches('-');
                if digits.len() > 1 && digits.starts_with('0') && !digits[1..].starts_with(['.', 'e', 'E']) {
                    return Err(format!("leading zero in {t}"));
                }
                Ok(V::Num(t))
            }
            _ => Err(format!("unexpected {:?} at {i}", c as char)),
        }
    }

    /// Compact JSON text of v (keys in order; strings escaped minimally).
    pub fn dump(v: &V) -> String {
        match v {
            V::Null => "null".into(),
            V::Bool(b) => b.to_string(),
            V::Num(n) => n.clone(),
            V::Str(s) => {
                let mut o = String::from("\"");
                for c in s.chars() {
                    match c {
                        '"' => o.push_str("\\\""),
                        '\\' => o.push_str("\\\\"),
                        c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
                        c => o.push(c),
                    }
                }
                o.push('"');
                o
            }
            V::Arr(a) => format!("[{}]", a.iter().map(dump).collect::<Vec<_>>().join(",")),
            V::Obj(kv) => format!("{{{}}}", kv.iter().map(|(k, x)| format!("{}:{}", dump(&V::Str(k.clone())), dump(x))).collect::<Vec<_>>().join(",")),
        }
    }

    /// Checks v against the JSON-schema subset of constrain.pyi.
    pub fn validate(v: &V, s: &V) -> Result<(), String> {
        let get = |k: &str| s.get_opt(k);
        if let Some(e) = get("enum") {
            return if e.arr().contains(v) { Ok(()) } else { Err(format!("{v:?} not in enum")) };
        }
        if let Some(c) = get("const") {
            return if c == v { Ok(()) } else { Err(format!("{v:?} != const")) };
        }
        if let Some(any) = get("anyOf") {
            return if any.arr().iter().any(|x| validate(v, x).is_ok()) { Ok(()) } else { Err(format!("{v:?} matches no anyOf branch")) };
        }
        match (get("type").map(|t| t.str()), v) {
            (Some("string"), V::Str(_)) | (Some("boolean"), V::Bool(_)) | (Some("null"), V::Null) => Ok(()),
            (Some("number"), V::Num(_)) => Ok(()),
            (Some("integer"), V::Num(n)) if !n.contains(['.', 'e', 'E']) => Ok(()),
            (Some("array"), V::Arr(a)) => {
                let lo = get("minItems").map(|x| x.i64()).unwrap_or(0) as usize;
                let hi = get("maxItems").map(|x| x.i64() as usize);
                if a.len() < lo || hi.is_some_and(|h| a.len() > h) {
                    return Err(format!("{} items outside [{lo}, {hi:?}]", a.len()));
                }
                a.iter().try_for_each(|x| validate(x, get("items").unwrap()))
            }
            (Some("object"), V::Obj(kv)) => {
                let empty = V::Obj(Vec::new());
                let props = get("properties").unwrap_or(&empty).obj();
                for (k, x) in kv {
                    let Some((_, ps)) = props.iter().find(|(p, _)| p == k) else { return Err(format!("unexpected key {k}")) };
                    validate(x, ps)?;
                }
                if let Some(r) = get("required") {
                    for name in r.arr() {
                        if !kv.iter().any(|(k, _)| k == name.str()) {
                            return Err(format!("missing required {}", name.str()));
                        }
                    }
                }
                let mut seen = std::collections::HashSet::new();
                if !kv.iter().all(|(k, _)| seen.insert(k.clone())) {
                    return Err("duplicate key".into());
                }
                Ok(())
            }
            (t, v) => Err(format!("{v:?} is not of type {t:?}")),
        }
    }
}
